adminUser:
  password: local:ferocious-wardrobe-1592906936/adminUser:password
  username: admin
docker:
  email: ablazleon@gmail.com
  password: local:ferocious-wardrobe-1592906936/docker:password
  url: https://hub.docker.com/
  username: ablazleon
enableDocker: true
pipelineUser:
  email: ablazleon@gmail.com
  token: local:ferocious-wardrobe-1592906936/pipelineUser:token
  username: ablazleon
prow:
  hmacToken: local:ferocious-wardrobe-1592906936/prow:hmacToken
